/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Emoji: typeof import('./src/components/bar/emoji.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    InputLayout: typeof import('./src/components/InputLayout.vue')['default']
    Item: typeof import('./src/components/chat/Item.vue')['default']
    MessageItem: typeof import('./src/components/chat/MessageItem.vue')['default']
    MessageLayout: typeof import('./src/components/MessageLayout.vue')['default']
    MessageMenu: typeof import('./src/components/MessageMenu.vue')['default']
    My: typeof import('./src/components/My.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NewBrand: typeof import('./src/components/newBrand.vue')['default']
    NForm: typeof import('naive-ui')['NForm']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings.vue')['default']
    TimeItem: typeof import('./src/components/chat/TimeItem.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
    UseSocket: typeof import('./src/components/useSocket.vue')['default']
    Voice: typeof import('./src/components/bar/voice.vue')['default']
    VoiceChat: typeof import('./src/components/VoiceChat.vue')['default']
  }
}
