// @/assets/header下所有svg文件名
export const avatars = [
    "Afterclap-5.svg",
    "Afterclap-6.svg",
    "Afterclap-7.svg",
    "Afterclap-8.svg",
    "Afterclap-9.svg",
    "Cranks.svg",
    "Cranks-1.svg",
    "Cranks-2.svg",
    "Delivery boy.svg",
    "Delivery boy-1.svg",
    "Delivery boy-2.svg",
    "Delivery boy-3.svg",
    "Delivery boy-4.svg",
    "Delivery boy-5.svg",
    "E-commerce.svg",
    "E-commerce-1.svg",
    "E-commerce-2.svg",
    "Funny Bunny.svg",
    "Funny Bunny-1.svg",
    "Funny Bunny-2.svg",
    "Funny Bunny-3.svg",
    "Funny Bunny-4.svg",
    "Funny Bunny-5.svg",
    "Funny Bunny-6.svg",
    "Funny Bunny-7.svg",
    "Funny Bunny-8.svg",
    "Guacamole.svg",
    "Guacamole-1.svg",
    "Guacamole-2.svg",
    "Guacamole-3.svg",
    "Juicy.svg",
    "Juicy-1.svg",
    "No comments 3.svg",
    "No comments 4.svg",
    "No comments 5.svg",
    "No comments 6.svg",
    "No comments 7.svg",
    "No comments 8.svg",
    "No comments 9.svg",
    "No Comments.svg",
    "No Comments-1.svg",
    "No Comments-2.svg",
    "No Comments-3.svg",
    "No gravity.svg",
    "No gravity-1.svg",
    "No gravity-2.svg",
    "No gravity-3.svg",
    "OSLO.svg",
    "OSLO-1.svg",
    "OSLO-2.svg",
    "OSLO-3.svg",
    "OSLO-4.svg",
    "OSLO-5.svg",
    "OSLO-6.svg",
    "OSLO-7.svg",
    "OSLO-8.svg",
    "OSLO-9.svg",
    "OSLO-10.svg",
    "OSLO-11.svg",
    "OSLO-12.svg",
    "OSLO-13.svg",
    "OSLO-14.svg",
    "Teamwork.svg",
    "Teamwork-1.svg",
    "Teamwork-2.svg",
    "Teamwork-3.svg",
    "Teamwork-4.svg",
    "Teamwork-5.svg",
    "Teamwork-6.svg",
    "Teamwork-7.svg",
    "Teamwork-8.svg",
    "Upstream.svg",
    "Upstream-1.svg",
    "Upstream-2.svg",
    "Upstream-3.svg",
    "Upstream-4.svg",
    "Upstream-5.svg",
    "Upstream-6.svg",
    "Upstream-7.svg",
    "Upstream-8.svg",
    "Upstream-9.svg",
    "Upstream-10.svg",
    "Upstream-11.svg",
    "Upstream-12.svg",
    "Upstream-13.svg",
    "Upstream-14.svg",
    "Upstream-15.svg",
    "Upstream-16.svg",
    "Upstream-17.svg",
    "01.svg",
    "Afterclap.svg",
    "Afterclap-1.svg",
    "Afterclap-2.svg",
    "Afterclap-3.svg",
    "Afterclap-4.svg",
];

export const getAvatarFile = (avatar: any) => {
    return new URL(`../assets/header/${avatar}`, import.meta.url);
  };
  